@startuml{xemime.png}

package net.zero918nobita.Xemime.ast {
    class AssignNode {
    }

    AssignNode --|> ExprNode

    class BlockNode {
    }

    BlockNode --|> Node

    class DeclareNode {
    }

    DeclareNode --|> ExprNode

    class DotAssignNode {
    }

    DotAssignNode --|> Node

    class DotCallNode {
    }

    DotCallNode --|> Node

    class DotExprNode {
    }

    DotExprNode --|> Node

    class ExprNode {
    }

    ExprNode --|> Node

    class FuncallNode {
    }

    FuncallNode --|> Node

    class LambdaExprNode {
    }

    LambdaExprNode --|> Node

    class MinusNode {
    }

    MinusNode --|> Node

    class Node {
    }

    class NotNode {
    }

    NotNode --|> Node

    class Symbol {
    }

    Symbol --|> Node
}

package net.zero918nobita.Xemime.entity {
    class Address {
    }

    Address --|> Node
    Address ..|> java.lang.Comparable

    class Bool {
    }

    Bool --|> Handler

    class Closure {
    }

    Closure --|> Function

    class Default {
    }

    Default --|> Handler

    class Double {
    }

    Double --|> Handler

    class Function {
    }

    Function --|> Node

    class Handler {
    }

    Handler --|> Node

    class Int {
    }

    Int --|> Handler

    class Native {
    }

    Native --|> Function

    class Numeric {
    }

    Numeric --|> Handler

    class Str {
    }

    Str --|> Handler
}

package net.zero918nobita.Xemime.interpreter {
    class Frame {
    }

    class Main {
    }
}

package net.zero918nobita.Xemime.lexer {
    class Lexer {
    }

    class LexerReader {
    }

    enum TokenType {
        T
        NIL
        INT
        DOUBLE
        STRING
        SYMBOL
        DECLARE
        ASSIGN
        SEMICOLON
        COMMA
        EOS
        ADD
        SUB
        MUL
        DIV
        EQ
        EQL
        NE
        L
        LE
        G
        GE
        AND
        OR
        XOR
        NOT
        LP
        RP
        LB
        RB
        LAMBDA
        ARROW
        PERIOD
    }
}

package net.zero918nobita.Xemime.parser {
    class Args {
    }

    Args --|> ParseUnit

    class Block {
    }

    Block --|> ParseUnit

    class DivideByZeroError {
    }

    DivideByZeroError --|> Exception

    class Expr {
    }

    Expr --|> ParseUnit

    class Factor {
    }

    Factor --|> ParseUnit

    class FatalError {
    }

    FatalError --|> Exception

    class First {
    }

    First --|> ParseUnit

    class Lambda {
    }

    Lambda --|> ParseUnit

    class MethodCall {
    }

    MethodCall --|> ParseUnit

    class Parser {
    }

    class ParseUnit {
    }

    class SimpleExpr {
    }

    SimpleExpr --|> ParseUnit

    class Statement {
    }

    Statement --|> ParseUnit

    class SyntaxError {
    }

    SyntaxError --|> Exception

    class Term {
    }

    Term --|> ParseUnit
}

package net.zero918nobita.Xemime.resolver {
    class Resolver {
    }

    class Scope {
    }

    class SemanticError {
    }

    SemanticError --|> Exception
}

package net.zero918nobita.Xemime.utils {
    class VirtualMemoryMonitor {
    }
}

@enduml
