@startuml{xemime.png}

package net.zero918nobita.Xemime.ast {
    class AssignNode {
    }

    class BlockNode {
    }

    class DeclareNode {
    }

    class DotAssignNode {
    }

    class DotCallNode {
    }

    class DotExprNode {
    }

    class ExprNode {
    }

    class LambdaExprNode {
    }
}

package net.zero918nobita.Xemime.interpreter {
    class Frame {
    }

    class Main {
    }
}

package net.zero918nobita.Xemime.lexer {
    class Lexer {
    }

    class LexerReader {
    }
}

package net.zero918nobita.Xemime.parser {
    class Parser {
    }
}

package net.zero918nobita.Xemime.resolver {
    class Resolver {
    }
}

package net.zero918nobita.Xemime.utils {
    class VirtualMemoryMonitor {
    }
}

/'
package net.zero918nobita.Xemime {

    class Frame {
    }

    class Lexer {
        -line
        -tokenType
        -val
        -reader
        Lexer()
        getLocation()
        advance()
        tokenType()
        value()
        -lexDigit()
        -lexString()
        -lexSymbol()
        -skipWhiteSpace()
        -skipLineComment()
        -skipComment()
    }

    Lexer --> LexerReader : -reader

    class LexerReader {
    }

    +class Main {
    }

    Main --> TokenType : -tokenType
    Main --> Parser : -parser

    class Parser {
    }

    Parser --> Lexer : -lex

    enum TokenType {
        T
        NIL
        INT
        DOUBLE
        STRING
        SYMBOL
        DECLARE
        ASSIGN
        SEMICOLON
        COMMA
        EOS
        ADD
        SUB
        MUL
        DIV
        EQ
        EQL
        NE
        L
        LE
        G
        GE
        AND
        OR
        XOR
        NOT
        LP
        RP
        LB
        RB
        LAMBDA
        ARROW
        PERIOD
    }

    +class VirtualMemoryMonitor {
    }

    VirtualMemoryMonitor --|> javafx.application.Application

    class X_Address {
    }

    X_Address --|> X_Code
    X_Address ..|> java.lang.Comparable

    class X_Assign {
    }

    X_Assign --|> X_BinExpr

    class X_BinExpr {
    }

    X_BinExpr --|> X_Code

    class X_Block {
    }

    X_Block --|> X_Code

    class X_Bool {
    }

    X_Bool --|> X_Handler

    class X_Closure {
    }

    X_Closure --|> X_Function

    class X_Code {
    }

    class X_Declare {
    }

    X_Declare --|> X_BinExpr

    class X_Default {
    }

    X_Default --|> X_Handler

    class X_DotAssign {
    }

    X_DotAssign --|> X_Code

    class X_DotCall {
    }

    X_DotCall --|> X_Code

    class X_DotExpr {
    }

    X_DotExpr --|> X_Code

    class X_Double {
    }

    X_Double --|> X_Numeric

    class X_Funcall {
    }

    X_Funcall --|> X_Code

    class X_Function {
    }

    X_Function --|> X_Code

    class X_Handler {
    }

    X_Handler --|> X_Code

    class X_Int {
    }

    X_Int --|> X_Numeric

    class X_LambdaExpr {
    }

    X_LambdaExpr --|> X_Code

    class X_Minus {
    }

    X_Minus --|> X_Code

    class X_Native {
    }

    X_Native --|> X_Function

    class X_Not {
    }

    X_Not --|> X_Code

    class X_Numeric {
    }

    X_Numeric --|> X_Handler

    class X_String {
        -String value
    }

    X_String --|> X_Handler

    class X_Symbol {
    }

    X_Symbol --|> X_Code
}
'/
@enduml
